version: "3"
services: 

  db:
    image: postgres:11-alpine
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    logging: 
      driver: "none"
    restart: unless-stopped
    volumes:
        - db-data:/var/lib/postgresql/data
          
  wiki:
    image: requarks/wiki:2.4
    depends_on: 
      - db
    environment: 
      WIKI_ADMIN_EMAIL: ${WIKI_ADMIN_EMAIL}
    restart: unless-stopped
    ports: 
      - "80:3000"
      - "443:3443"
    volumes: 
      - $HOME/WikiJSExample/config.yml:/wiki/config.yml
      - $HOME/WikiJSExample/github.pem:/wiki/github.pem

volumes:
  db-data:
